# Generated by Django 2.0.6 on 2018-06-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('technologies_used', models.CharField(max_length=255)),
                ('link_to_ms_github_repository', models.CharField(max_length=255)),
                ('project_desription', models.CharField(max_length=255)),
            ],
        ),
    ]
