# Generated by Django 2.0.6 on 2018-06-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='link_to_ms_github_repository',
            new_name='github_link',
        ),
    ]
