# Generated by Django 2.0.6 on 2018-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180605_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_desription',
            field=models.TextField(null=True),
        ),
    ]
