# Generated by Django 2.0.6 on 2018-06-06 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180606_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Project',
        ),
    ]
